apiVersion: v1
kind: Pod
metadata:
  name: joplin-cron
  namespace: {{ .Values.namespace }}
spec:
  dnsPolicy: ClusterFirst
  dnsConfig:
    options:
      - name: ndots
        value: "1"
  containers:
  - name: joplin-cron
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
    volumeMounts:
    - name: notes-data
      mountPath: /notes_data
    - name: accounts
      mountPath: /config
  volumes:
    - name: notes-data
      persistentVolumeClaim:
        claimName: notes-data-pvc
    - name: accounts
      configMap:
        name: joplin-backup-accounts
	
