apiVersion: v1
kind: Pod
metadata:
  name: joplin-cron
  namespace: {{ .Values.namespace }}
spec:
  dnsPolicy: ClusterFirst
  dnsConfig:
    options:
      - name: ndots
        value: "1"
  containers:
  - name: ubuntu
    image: ubuntu:24.04
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
    env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: joplin-cron-secrets
          key: postgres_password
    volumeMounts:
    - name: notes-data
      mountPath: /notes_data
  volumes:
    - name: notes-data
      persistentVolumeClaim:
        claimName: notes-data-pvc
