apiVersion: v1
kind: ConfigMap
metadata:
  name: joplin-emelz-secrets
  namespace: default
  labels:
    app: joplin-emelz
    component: secrets
data:
  jwt_secret: {{ .Values.secrets.jwtSecret | quote }}
  postgres_password: {{ .Values.secrets.postgresPassword | quote }}