apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-joplin-emelz-joplin
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-hostpath
  hostPath:
    path: {{ .Values.storage.hostPath.joplinData }}
  claimRef:
    name: pvc-joplin-emelz-joplin
    namespace: default
