apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-joplin-emelz-jwt-secret
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-hostpath
  hostPath:
    path: {{ .Values.storage.hostPath.jwtSecret }}
  claimRef:
    name: pvc-joplin-emelz-jwt-secret
    namespace: default
