apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-joplin-emelz-jwt-secret
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-joplin-emelz-jwt-secret
