apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joplin-emelz-pvc-joplin
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: joplin-emelz-pv-joplin
