apiVersion: v1
kind: Service
metadata:
  name: joplin-emelz
  namespace: default
spec:
  selector:
    app: joplin-emelz
  ports:
  - name: p22300
    port: 22300
    targetPort: 22300
    protocol: TCP
  type: LoadBalancer
