apiVersion: v1
kind: Service
metadata:
  name: joplin-emelz
  namespace: {{ .Values.namespace }}
  labels:
    app: joplin-emelz
    environment: {{ .Values.environment }}
spec:
  selector:
    app: joplin-emelz
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.app.port }}
    protocol: TCP
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  type: {{ .Values.service.type }}
