# Default values - override with environment-specific values
environment: local
namespace: default

# Application configuration
app:
  baseUrl: http://localhost:22300
  port: 22300
  cookieSecure: false
  jwtSecretFile: /run/secrets/jwt_secret

# Database configuration
database:
  client: pg
  host: localhost
  port: 5432
  name: joplin
  user: joplin

# Mailer configuration
mailer:
  enabled: 1
  host: smtp.gmail.com
  port: 587
  security: starttls
  authUser: no-reply@emelz.org
  noreplyEmail: no-reply@emelz.org
  noreplyName: Joplin
  
# Storage configuration
storage:
  type: hostPath  # hostPath, dynamic, or pvc
  className: manual-hostpath
  size: 10Gi
  hostPath: /mnt/var/joplin-server/data

# Service configuration
service:
  type: LoadBalancer
  port: 22300
  nodePort: null

# Ingress configuration
ingress:
  enabled: false
  className: ""
  host: ""
  tls: false

# Resource configuration
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

replicas: 1

# Encrypted secrets (populated by deployment scripts)
secrets:
  jwtSecret: ""  # Will be populated from encrypted secrets file
  postgresPassword: ""  # Will be populated from encrypted secrets file