deploymentEnv: dev
appPort: 22300
appBaseUrl: http://localhost:22300
cookieSecure: false
dbClient: pg
postgresHost: 100.102.105.59
postgresPort: 55434
postgresDatabase: joplin
postgresUser: joplin
postgresPassword: ""
postgresPasswordFile: /run/secrets/pg_password
jwtSecretFile: /run/secrets/jwt_secret

storage:
  hostPath:
    jwtSecret: /mnt/var/joplin-server/secrets/.jwt_secret
    joplinData: /mnt/var/joplin-server/data