apiVersion: v1
kind: Secret
metadata:
  name: compose-app-joplin-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  JWT_SECRET_FILE: ${JWT_SECRET_FILE}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: compose-app-joplin-pv-aa41cb5c
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/ericmelz/bin/joplin-server/data
  claimRef:
    name: compose-app-joplin-pvc-aa41cb5c
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compose-app-joplin-pvc-aa41cb5c
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: compose-app-joplin-pv-aa41cb5c
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: compose-app-joplin-pv-a0503fd2
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/ericmelz/Data/secrets/.jwt_secret
  claimRef:
    name: compose-app-joplin-pvc-a0503fd2
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compose-app-joplin-pvc-a0503fd2
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: compose-app-joplin-pv-a0503fd2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compose-app-joplin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compose-app-joplin
  template:
    metadata:
      labels:
        app: compose-app-joplin
    spec:
      containers:
      - name: joplin
        image: joplin/server:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_PORT
          value: ${APP_PORT}
        - name: APP_BASE_URL
          value: ${APP_BASE_URL}
        - name: DB_CLIENT
          value: ${DB_CLIENT}
        - name: POSTGRES_HOST
          value: ${POSTGRES_HOST}
        - name: POSTGRES_PORT
          value: ${POSTGRES_PORT}
        - name: POSTGRES_DATABASE
          value: ${POSTGRES_DATABASE}
        - name: POSTGRES_USER
          value: ${POSTGRES_USER}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: compose-app-joplin-secret
              key: POSTGRES_PASSWORD
        - name: JWT_SECRET_FILE
          valueFrom:
            secretKeyRef:
              name: compose-app-joplin-secret
              key: JWT_SECRET_FILE
        volumeMounts:
        - name: compose-app-joplin-joplin
          mountPath: /home/joplin/.joplin
          readOnly: false
        - name: compose-app-joplin-jwt-secret
          mountPath: /run/secrets/jwt_secret
          readOnly: true
        ports:
        - containerPort: 22300
          protocol: TCP
      volumes:
      - name: compose-app-joplin-joplin
        persistentVolumeClaim:
          claimName: compose-app-joplin-pvc-aa41cb5c
      - name: compose-app-joplin-jwt-secret
        persistentVolumeClaim:
          claimName: compose-app-joplin-pvc-a0503fd2
---
apiVersion: v1
kind: Service
metadata:
  name: compose-app-joplin
  namespace: default
spec:
  selector:
    app: compose-app-joplin
  ports:
  - name: p22300
    port: 22300
    targetPort: 22300
    protocol: TCP
  type: NodePort
