apiVersion: apps/v1
kind: Deployment
metadata:
  name: compose-app-joplin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compose-app-joplin
  template:
    metadata:
      labels:
        app: compose-app-joplin
    spec:
      containers:
      - name: joplin
        image: joplin/server:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_PORT
          value: ${APP_PORT}
        - name: APP_BASE_URL
          value: ${APP_BASE_URL}
        - name: DB_CLIENT
          value: ${DB_CLIENT}
        - name: POSTGRES_HOST
          value: ${POSTGRES_HOST}
        - name: POSTGRES_PORT
          value: ${POSTGRES_PORT}
        - name: POSTGRES_DATABASE
          value: ${POSTGRES_DATABASE}
        - name: POSTGRES_USER
          value: ${POSTGRES_USER}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: compose-app-joplin-secret
              key: POSTGRES_PASSWORD
        - name: JWT_SECRET_FILE
          valueFrom:
            secretKeyRef:
              name: compose-app-joplin-secret
              key: JWT_SECRET_FILE
        volumeMounts:
        - name: compose-app-joplin-joplin
          mountPath: /home/joplin/.joplin
          readOnly: false
        - name: compose-app-joplin-jwt-secret
          mountPath: /run/secrets/jwt_secret
          readOnly: true
        ports:
        - containerPort: 22300
          protocol: TCP
      volumes:
      - name: compose-app-joplin-joplin
        persistentVolumeClaim:
          claimName: compose-app-joplin-pvc-aa41cb5c
      - name: compose-app-joplin-jwt-secret
        persistentVolumeClaim:
          claimName: compose-app-joplin-pvc-a0503fd2
