apiVersion: v1
kind: PersistentVolume
metadata:
  name: compose-app-joplin-pv-a0503fd2
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/ericmelz/Data/secrets/.jwt_secret
  claimRef:
    name: compose-app-joplin-pvc-a0503fd2
    namespace: default
