apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compose-app-joplin-pvc-aa41cb5c
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: compose-app-joplin-pv-aa41cb5c
