apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compose-app-joplin-pvc-a0503fd2
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: compose-app-joplin-pv-a0503fd2
