apiVersion: v1
kind: PersistentVolume
metadata:
  name: compose-app-joplin-pv-aa41cb5c
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/ericmelz/bin/joplin-server/data
  claimRef:
    name: compose-app-joplin-pvc-aa41cb5c
    namespace: default
