apiVersion: v1
kind: Service
metadata:
  name: compose-app-joplin
  namespace: default
spec:
  selector:
    app: compose-app-joplin
  ports:
  - name: p22300
    port: 22300
    targetPort: 22300
    protocol: TCP
  type: NodePort
